version: 0.0
os: linux
files:
  - source: app.jar
    destination: /opt/tomcat/app

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
