version: 0.0 
os: linux 
ECHO is on.
files: 
"  - source: target/demo-0.0.1-SNAPSHOT.jar" 
"    destination: /opt/demo" 
ECHO is on.
hooks: 
"  ApplicationStop:" 
"    - location: scripts/stop.sh" 
"      timeout: 60" 
"      runas: ec2-user" 
"  AfterInstall:" 
"    - location: scripts/start.sh" 
"      timeout: 60" 
"      runas: ec2-user" 
